# Generated by Django 3.2.9 on 2021-12-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default='noone', max_length=255),
        ),
    ]
